### ISSUE TITLE
🪧 Frontend: init works for Leading page or IM Apps

### ISSUE THREAD

**Issue by George-Miao** [Limit-IM/limit-site#5]
> Instruction Cards, Initial work phase, (maybe always in progress)

- [ ] ~~🤔 Planning for new leading page contents (docs: https://hackmd.io/egIl0DKrTbmzDTrSBG12kA)~~
- [x] ~~♻️ (Optional) Check & resolve current limit-site problems )~~
- [x] ~~📦 Create repo for "IM-FE" apps.~~

## Repos
- 📦 https://github.com/Limit-LAB/limit-frontend

**Comment by u-u-z** [comment]
FE repo init in https://github.com/Limit-LAB/limit-frontend
Leading page works need after: https://github.com/Limit-LAB/prod-docs/issues/2 & https://github.com/Limit-LAB/prod-docs/issues/1
